source 'https://rubygems.org'

# Specify your gem's dependencies in cucumber.gemspec
gemspec

group :development, :test do
  gem "rspec-rails", ">= 2.0.1"
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'json', '~> 1.7.7'
end
